### ISSUE TITLE
Usage of is_components 

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#8]
Hello, 

could you tell me, what the meaning of is_components property exactly is. 

The reasom is, that I had some trouble with this property, i.e. is_components is set to True for indices in MagFEMM\build_meshsolution method (line 33), while I consider indices not to be a component.
`Indices_Cell = Data1D(name="indice", values=indices_cell, is_components=True)`

With is_components set to False, I was not able to get specific indices `'indice[1, 2, 3,...]'` of the fields components with get_alone method on a VectorField (e.g. x component of out.mag.B). It only works when is_components of indices is set True.

Best regards, Sebastian

**Comment by helene-t** [comment]
Hello Sebastian,

`is_components` is a key used to make sure that the values of the axis are never used in a mathematical operation (e.g. indices of a mesh, "A", "B", "C" for the current phases, etc. must not be interpolated). It is true that the name of this parameter is not very well chosen. Maybe I could rename it as "is_not_numbers"?

I am currently working on many improvements and will release a new version soon. In particular `get_along` methods will return all axes (e.g. sliced axes will be returned as the single value used for the slice), so that you should be able to get indices even with `is_components=False`.

Best regards, Hélène

**Comment by SebGue** [comment]
Hello Hélène,

Thank you for your explanation. I think you should not rename this parameter, but add your explanation to the class property description and to the tutorial nr. 1 would be helpful.

BR, Sebastian
