### ISSUE TITLE
[NF] Inverse FFT of sparse spectrum

### ISSUE THREAD

**Issue by EmileDvs** [Eomys/SciDataTool#9]
Hello,

This issue aims at calculating the time/space domain signal from a sparse spectrum contained in a DataFreq object using get_along() method, providing time/space vectors are given as input, for example following the existing syntax:

`DataFreq.get_along("time=axisdata", space="axisdata", axis_data={"time"=time_vector, "space"=space_vector})`

Basically the method would sum on all the time/space harmonics magnitudes multiplied by the cosine at the proper time/space frequency.

Best regards,

Emile

**Comment by helene-t** [comment]
Hi everyone,

We are planning to tackle this issue shortly. We would like to also address the issue of non-uniform sampling in fft/ifft at the same time. We are currently investigating NUFFT python packages. There are 3 types of NUFFT: 
- non-uniform time series and uniform frequency series
- uniform time series and non-uniform frequency series
- non-uniform time series and non-uniform frequency series

The idea would be to provide time and/or frequency series as an input data (using axis_data as suggested by Emile) as a first step. The NUFFT type could then be deduced from the data provided. A second step could be to compute those series in order to optimize memory storage, computation time and accuracy.

We plan to implement this functionality into the fft_functions script, as a sub-method of comp_fftn and comp_ifftn. We would not need to modify comp_fft_freq and comp_fft_time in this first step, as they will be provided by the user.
